apiVersion: v1
kind: PersistentVolume
metadata:
  name: cbcd-shared-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: /mnt/nfs_share
    server: 34.85.228.110
