apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbcd-shared-pv
  namespace: cbcd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: cbcd-shared-pv
  resources:
    requests:
      storage: 15Gi
