apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flow-server-shared
  namespace: cbcd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: flow-server-shared
  resources:
    requests:
      storage: 15Gi
